all:
	g++ -c -pedantic -std=c++11 -Wall AR1_model.cpp
	g++ -c -pedantic -std=c++11 -Wall SIS_corrections.cpp
	#g++ -c -pedantic -std=c++11 -Wall AR1_sim_and_int.cpp
	g++ AR1_model.o SIS_corrections.o -o AR1_simulation

